### PR TITLE
feat: Add the "s3fs.proxy.protocol" environment variable.

### LINKED ISSUE #719: The "s3fs.protocol" environment variable applies to both the S3 client and the Proxy.
Thank you for continuing to maintain the source code forked from Upplication/Amazon-S3-FileSystem-NIO2. Your efforts are greatly appreciated.

# Bug Description
The "s3fs.protocol" environment variable applies to both the S3 client and the Proxy. Therefore, if the S3 client uses HTTPS and the Proxy uses HTTP, they must use unified protocol. This behavior can be problematic in environments where it is not possible to change the Proxy settings.

# Expected Behavior
I would like to separate the configuration of S3 and Proxy protocols.

# Environment

* `s3fs-nio` version:1.0.1
* OS: not relevant
* JDK: not relevant

# A patch for my environment.

Below is the patch I created for my development environment. Although it is a tricky modification, I only changed the S3Factory.class, which has a clear scope of effect. If the changes below are OK, I would like to create a pull request.

``` java
// In org.carlspring.cloud.storage.s3fs.S3Factory.java
    public static final String PROXY_PROTOCOL = "s3fs.proxy.protocol"; // add a new constant

    protected ProxyConfiguration getProxyConfiguration(final Properties props)
    {


        final ProxyConfiguration.Builder builder = ProxyConfiguration.builder();

        if (props.getProperty(PROXY_HOST) != null)
        {
            final String host = props.getProperty(PROXY_HOST);
            final String portStr = props.getProperty(PROXY_PORT);
            int port = -1;
            try
            {
                port = portStr != null ? Integer.parseInt(portStr, RADIX) : -1;
            }
            catch (final NumberFormatException e)
            {
                printWarningMessage(props, PROXY_PORT);
            }
// modification start
           // Calls the getEndpointUri method after setting the PROTOCOL property to the value of PROXY_PROTOCOL.
           final Properties propsCopy = new Properties();
           for (String key : props.stringPropertyNames()) {
               propsCopy.setProperty(key, props.getProperty(key));
           }

            if (propsCopy.getProperty(PROXY_PROTOCOL) != null)
            {
            	propsCopy.setProperty(PROTOCOL, props.getProperty(PROXY_PROTOCOL));
            }
            final URI uri = getEndpointUri(host, port, propsCopy);
// modification end
            builder.endpoint(uri);
        }

```

### PR DESCRIPTION
**Pull request by stanakaj**
# Pull Request Description

This pull request closes #719 .

# Acceptance Test

* [x] Building the code with `gradle clean build` still works.

# Questions

* Does this pull request break backward compatibility? 
  * [x] Yes and my commit follows the [Conventional Commits Specification](https://www.conventionalcommits.org/en/v1.0.0/)
  * [ ] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [x] Yes, please see [need to add the "s3fs.proxy.protocol" environment variable]
  * [ ] No

### CODE REVIEW

**Comment by stanakaj** [comment]
It seems that the s3fs.region setting is missing in the test. Please let me know if there is anything I can do to help.
```
    java.lang.IllegalArgumentException: region must not be blank or empty.
        at software.amazon.awssdk.utils.Validate.paramNotBlank(Validate.java:159)
        at software.amazon.awssdk.regions.Region.of(Region.java:136)
```

**Comment by steve-todorov** [comment]
Hey @stanakaj ,

Thank you very much for your contribution! :) 

I believe that might be a false-positive exception related to how GH Actions runs workflows from forks (secrets are usually not passed to forks). I will check your PR manually in the upcoming days.

// cc @carlspring ICLA?

**Comment by stanakaj** [comment]
I added some test codes in S3ClientFactoryTest. The "differntProtocols" test is my proxy configuration scenario.

**Comment by steve-todorov** [comment]
Thanks for your contribution @stanakaj ! :)

**Pull request merged**
